version: '3.8'

services:
  dispatch-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: go-dispatch-proxy-enhanced
    
    # Use host networking for full network access
    network_mode: host
    
    # Volumes for persistent data
    volumes:
      - ./data:/app/data              # Database and config persistence
      - ./logs:/app/logs              # Log files (if needed)
      - /etc/localtime:/etc/localtime:ro  # Sync container time with host
    
    # Required capabilities for network operations
    cap_add:
      - NET_RAW
      - NET_ADMIN
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8095/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Labels for better organization
    labels:
      - "traefik.enable=false"  # Disable Traefik if running
      - "com.example.description=Go Dispatch Proxy Enhanced"
      - "com.example.version=3.0"